object VKForm: TVKForm
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'Virtual Keyboard'
  ClientHeight = 450
  ClientWidth = 350
  Color = clSilver
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -24
  Font.Name = 'Segoe UI'
  Font.Style = [fsBold]
  Position = poMainFormCenter
  TextHeight = 32
  object EditValue: TEdit
    Left = 10
    Top = 10
    Width = 330
    Height = 50
    Alignment = taRightJustify
    Color = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clLime
    Font.Height = -32
    Font.Name = 'Consolas'
    Font.Style = [fsBold]
    ParentFont = False
    ReadOnly = True
    TabOrder = 0
    Text = '0,00'
  end
  object PanelKeys: TPanel
    Left = 10
    Top = 70
    Width = 330
    Height = 370
    BevelOuter = bvNone
    Color = clSilver
    ParentBackground = False
    TabOrder = 1
    object Btn7: TPanel
      Left = 0
      Top = 0
      Width = 100
      Height = 70
      Caption = '7'
      Color = clBlack
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 0
      OnClick = PanelBtnClick
    end
    object Btn8: TPanel
      Left = 110
      Top = 0
      Width = 100
      Height = 70
      Caption = '8'
      Color = clBlack
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 1
      OnClick = PanelBtnClick
    end
    object Btn9: TPanel
      Left = 220
      Top = 0
      Width = 100
      Height = 70
      Caption = '9'
      Color = clBlack
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 2
      OnClick = PanelBtnClick
    end
    object Btn4: TPanel
      Left = 0
      Top = 80
      Width = 100
      Height = 70
      Caption = '4'
      Color = clBlack
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 3
      OnClick = PanelBtnClick
    end
    object Btn5: TPanel
      Left = 110
      Top = 80
      Width = 100
      Height = 70
      Caption = '5'
      Color = clBlack
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 4
      OnClick = PanelBtnClick
    end
    object Btn6: TPanel
      Left = 220
      Top = 80
      Width = 100
      Height = 70
      Caption = '6'
      Color = clBlack
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 5
      OnClick = PanelBtnClick
    end
    object Btn1: TPanel
      Left = 0
      Top = 160
      Width = 100
      Height = 70
      Caption = '1'
      Color = clBlack
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 6
      OnClick = PanelBtnClick
    end
    object Btn2: TPanel
      Left = 110
      Top = 160
      Width = 100
      Height = 70
      Caption = '2'
      Color = clBlack
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 7
      OnClick = PanelBtnClick
    end
    object Btn3: TPanel
      Left = 220
      Top = 160
      Width = 100
      Height = 70
      Caption = '3'
      Color = clBlack
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 8
      OnClick = PanelBtnClick
    end
    object Btn0: TPanel
      Left = 0
      Top = 240
      Width = 100
      Height = 70
      Caption = '0'
      Color = clBlack
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 9
      OnClick = PanelBtnClick
    end
    object BtnComma: TPanel
      Left = 110
      Top = 240
      Width = 100
      Height = 70
      Caption = ','
      Color = clBlack
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 10
      OnClick = BtnCommaClick
    end
    object BtnClear: TPanel
      Left = 220
      Top = 240
      Width = 100
      Height = 70
      Caption = 'CLR'
      Color = clWhite
      Font.Color = clBlack
      ParentBackground = False
      TabOrder = 11
      OnClick = BtnClearClick
    end
    object BtnCancel: TPanel
      Left = 0
      Top = 320
      Width = 100
      Height = 50
      Caption = 'CANCEL'
      Color = clMaroon
      Font.Color = clWhite
      Font.Height = -16
      ParentBackground = False
      TabOrder = 12
      OnClick = BtnCancelClick
    end
    object BtnEnter: TPanel
      Left = 110
      Top = 320
      Width = 210
      Height = 50
      Caption = 'SEND'
      Color = clHighlight
      Font.Color = clWhite
      ParentBackground = False
      TabOrder = 13
      OnClick = BtnEnterClick
    end
  end
end
